project_name: sbomasm

version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: true 

builds:
  - id: binaries 
    binary: sbomasm-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true 
    main: .
    flags:
      - -trimpath 
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows 
    goarch:
      - amd64
      - arm64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env: 
      - CGO_ENABLED=0

nfpms:
  - id: sbomasm
    package_name: sbomasm
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Interlynk
    homepage: https://interlynk.io
    maintainer: Interlynk Authors hello@interlynk.io
    builds:
      - binaries
    description: SBOM Assembler - A tool to edit SBOM or assemble multiple sboms into a single sbom.
    license: "Apache License 2.0"
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: /usr/bin/sbomasm-{{ .Os }}-{{ .Arch }}
        dst: /usr/bin/sbomasm
        type: "symlink"

archives:
- format: binary
  name_template: "{{ .Binary }}"
  allow_different_binary_count: true 

snapshot: 
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: allow 
  draft: true 

